### ISSUE TITLE
Can't badge tvOS icons

### ISSUE THREAD

**Issue by faithfracture** [HazAT/badge#31]
README.md claims badge works for tvOS projects, but if I run badge in my tvOS project directory, all I get is a `Could not find any app icons...` message.

**Comment by dcordero** [comment]
@faithfracture due to the fact that tvOS icons are parallax icons, which are actually composed by 3 different images (Front, Middle and Back), the badge or shield could be applied to any of them depending on the design.

That is why badge needs to be adjusted using the parameter  `--glob=` which indicates where to find the icon.

For example:
`badge --glob="/**/Front.imagestacklayer/Content.imageset/*.{png,PNG}"`

Would apply the badge to the Front image of the parallax icon.

**Comment by faithfracture** [comment]
Ah, ok. I do see that now under the Usage section. Thanks!
