### ISSUE TITLE
Could not find app icons with glob option

### ISSUE THREAD

**Issue by elvin-vega** [HazAT/badge#83]
@HazAT I'm using badge (version 1.1.0) with glob option. 

Badge throw a message "Could not find any app icons...". Below is the badge command I'm using:
`badge --shield "Version:-3.5.0.318-blue" --dark true --shield_no_resize true --glob /Users/<HOME_FOLDER>/Dev/source/Images/Images.xcassets/AppIcon.appiconset/*.{png,PNG}" `

Same behavior using fastlane_plugin_badge. Below is how I have it configure in fastfile:
`add_badge(`
`        shield: "Version:-3.5.0.318-blue", `
`        dark: true, `
`        glob: "/Users/<HOME_FOLDER>/Dev/source/Images/Images.xcassets/AppIcon.appiconset/*.{png,PNG}" `
`      )`

The funny thing is if I copy the app icons at `/Users/<HOME_FOLDER>/Dev/configuredProjects/iOS_Project/AppIcon.appiconset` badge and fastlane_plugin_badge works as expected. 

Fastlane root folder located at `/Users/<HOME_FOLDER>/Dev/configuredProjects/fastlane`.

Here example working command:
`badge --shield "Version:-3.5.0.318-blue" --dark true`

`add_badge(`
`        shield: "Version:-3.5.0.318-blue", `
`        dark: true, `
`      )`

What is causing `glob` option is not working as expected given a path outside the fastlane root folder?

**Comment by HazAT** [comment]
Because I coded it badly, I probably gonna make a breaking change release changing this because many people run into this.

It's because of this:
https://github.com/HazAT/badge/blob/cf668aac56b6144d75c12ddee7acbac22a2a1462/lib/badge/runner.rb#L16

I always prepend the current path, simple fix would be to check if the passed path into glob contains a trailing slash and then don't do it, but it would be a breaking change.
